Adds shapely return object for isochrone and geodataframes for clusters
askiggy/iggy-api-python pull request #3
Opened 2021-02-24 23:52 UTC by zhaovan

Solves first two on this page: https://www.notion.so/askiggy/Data-product-Python-API-module-fbfe7765ef7845b59cbbf7715eab2399

Adds shapely polygons for /isochrone endpoint and geodataframes for /clusters

2021-02-25 15:23 UTC, acocos requested changes
Thanks for getting this started @zhaovan !

I like your suggestion to provide options in `/isochrone` and `/clusters` to either return the raw response, or the GeoDataFrame version. Let's do it.

Also, before we merge this, let's make sure to update the version number in `setup.py`. I neglected to do this in my last merge, and as a result I think there are some caching issues with getting the latest version of our library from pypi.

I added some notes about ways to make the conversion to GeoDataFrame cleaner. Other than that, looks great!

2021-02-25 15:23 UTC, acocos commented on iggyapi/api.py
> +    def isochrone(self, options: Dict) -> sg.Polygon:
Looking at this again, for consistency's sake, what would you think about having this return a (one-row) GeoDataFrame instead of a sg.Polygon?

You could do this in two lines with something like:
```
response = self.enrich("isochrone", options)
gdf = gpd.GeoDataFrame.from_features([response])
```

2021-02-25 15:23 UTC, acocos commented on iggyapi/api.py
> +        names = [None] * num_clusters
Would be cleaner to gather the `names` and geometries using list comprehensions over the clusters, e.g.
```
names = [c['summary']['place_names'] for c in response['clusters']]
geoms = [c['geojson'] for c in response['clusters']]
```
Then you can collapse both into a GeoDataFrame with something like:
```
gdf = gpd.GeoDataFrame.from_features(geoms)
gdf['names'] = names
```

2021-02-25 15:23 UTC, acocos commented on iggyapi/api.py
> +            line_dist[i] = response["clusters"][i]["geojson"]
I don't think `straight_line_distance_miles` is in the properties for `/clusters` response

2021-02-25 21:32 UTC, bdejesus commented on iggyapi/api.py
> +api = IggyAPI("03886df9fb8f6306e2065fdc98f2080")
Is there a way to supply this API token without hardcoding it into this repo?

2021-02-26 21:36 UTC, acocos reviewed
Looks good @zhaovan! Just a couple minor cleanup things I noticed.

Let's update the `version` in `setup.py` and add the requirements to `install_requires` before merging and sending off to pypi

2021-02-26 21:36 UTC, acocos commented on iggyapi/api.py
> +        num_clusters = len(response["clusters"])
line can be removed

2021-02-26 21:36 UTC, acocos commented on iggyapi/api.py
> +    def isochrone(self, options: Dict) -> sg.Polygon:
Need to update definition to show it outputs a `gdf.GeoDataFrame` or `Dict`, e.g.
```
from typing import Dict, Union

def isochrone(self, options: Dict) -> Union[Dict, gdf.GeoDataFrame]:
...
```

2021-02-26 21:36 UTC, acocos commented on README.md
> +For certain endpoints (specifically /isochrone and /clusters), the results come back as a GeoDataFrame by default (for ease of access). If you would instead like the raw response, add the key-value p
Should this say ` "raw_response": True` to indicate you want the raw response?

2021-02-26 21:36 UTC, acocos commented on iggyapi/api.py
> +import shapely.geometry as sg
I think this import can be removed after changing the return types from `isochrone`

2021-02-26 22:28 UTC, acocos approved these changes

2021-02-26 22:28 UTC, merged